#!/bin/bash
# paragraph-space
# Inserts a blank line between paragraphs of a single-spaced text file
# Usage: $0 <FILENAME

#TODO 10-1

MINLEN=60

while read line; do
    echo "$line"

    #if [[ "${#line}" -lt "$MINLEN" && "$line" =~ \[*\.\] ]]; then
    if [[ "${#line}" -lt "$MINLEN" && "$line" =~ [*{\.}]$ ]]; then
        echo
    fi
done
