#!/bin/bash
# rpm-check

# Queries an rpm file for description, listing,
#+ and whether it can be installed.
# Saves output to a file.
#
# This script illustrates using a code block.


SUCCESS=0
E_NOARGS=65

if [ -z "$1" ]; then
    echo "Usage: `basename $0` rpm-file"
    exit $E_NOARGS
fi

{
    echo
    echo "Archive Description:"
    rpm -qpi $1  # Query description
    echo
    echo "Archive Listing:"
    rpm -qpl $1  # Query listing
    echo
    rpm -i --test $1  # Query whether rpm file can be installed
    [ "$?" -eq $SUCCESS ] \
        && echo "$1 can be installed" \
        || echo "$1 cannot be installed"
    echo
} > "$1.test"

echo "Results of rpm test in file $1.test"
