#!/bin/bash
# seeding-rand

SEED=

randNums() {
    COUNT=25
    for i in $(seq $COUNT); do
        echo -n "$RANDOM "
    done
}

clear
echo
SEED=1
RANDOM=$SEED
echo "seed = $SEED"
randNums

echo; echo
echo "Again, with same random seed ..."
RANDOM=$SEED
echo "seed = $SEED"
randNums

echo; echo
SEED=2
RANDOM=$SEED
echo "seed = $SEED"
randNums

echo; echo

SEED=$(head -1 /dev/urandom | od -N 1 | awk '{ print $2 }' | sed s/^0*// )
RANDOM=$SEED
echo "seed = $SEED"
randNums

echo
